
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = true
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	#Disables specific entries
	[general.entries]

		[general.entries.wood_type]

			[general.entries.wood_type.twigs]
				table = true

			[general.entries.wood_type.create]
				window_pane = true
				window = true

			[general.entries.wood_type.decorative_blocks]
				beam = true
				support = true
				seat = true
				palisade = true

			[general.entries.wood_type.furnish]
				coffin = true
				bedside_table = true
				cabinet = true
				log_bench = true
				kitchen_cabinet = true
				shelf = true
				wardrobe = true
				square_table = true
				bench = true
				crate = true
				table = true
				stool = true
				pedestal_table = true
				chair = true
				shutter = true
				ladder = true
				bookshelf_chest = true

			[general.entries.wood_type.regions_unexplored]
				branch = true

	#Disables certain types
	[general.types]

		[general.types.wood_type]

			[general.types.wood_type.born_in_chaos_v1]
				scorched = true

			[general.types.wood_type.regions_unexplored]
				alpha = true
				baobab = true
				blackwood = true
				blue_bioshroom = true
				brimwood = true
				cobalt = true
				cypress = true
				dead = true
				eucalyptus = true
				green_bioshroom = true
				joshua = true
				kapok = true
				larch = true
				magnolia = true
				maple = true
				mauve = true
				palm = true
				pine = true
				pink_bioshroom = true
				redwood = true
				socotra = true
				willow = true
				yellow_bioshroom = true

		[general.types.leaves_type]

			[general.types.leaves_type.regions_unexplored]
				bamboo = true
				golden_larch = true
				alpha = true
				apple_oak = true
				baobab = true
				blackwood = true
				magnolia = true
				cypress = true
				dead = true
				dead_pine = true
				eucalyptus = true
				flowering = true
				kapok = true
				larch = true
				maple = true
				mauve = true
				orange_maple = true
				palm = true
				pine = true
				blue_magnolia = true
				pink_magnolia = true
				redwood = true
				red_maple = true
				brimwood = true
				enchanted_birch = true
				small_oak = true
				silver_birch = true
				socotra = true
				white_magnolia = true
				willow = true
				ashen = true

